In [ ]:
import numpy as np
import pandas as pd

#Concat the data

In [ ]:
band_value_germany = pd.read_csv('band_value_germany.csv')
band_value_germany_latest = pd.read_csv('band_value_germany_latest.csv')
salinity_df = pd.read_csv('salinity_german_data.csv')

In [ ]:
# concat band_value_germany and band_value_germany_latest

import pandas as pd
band_df = pd.concat([band_value_germany, band_value_germany_latest], ignore_index=True)

In [ ]:
band_df.info()

In [ ]:
salinity_df.info()

In [ ]:
# band_df and salinity_df drop Unnamed: 0

band_df = band_df.drop('Unnamed: 0', axis=1)
salinity_df = salinity_df.drop('Unnamed: 0', axis=1)

In [ ]:
band_df['Date'] = pd.to_datetime(band_df['Date'])
salinity_df['Date'] = pd.to_datetime(salinity_df['Date'])

In [ ]:
#  salinity_df merge with band_df on date, latitude, longitude, station

import pandas as pd
merged_df = pd.merge(salinity_df, band_df, on=['Date', 'Latitude', 'Longitude', 'Station'], how='left')

In [ ]:
merged_df

,Date/Time,"Temp [°C] (CTD, Sea-Bird, SBE 37-SI Micr...)","Sal (CTD, Sea-Bird, SBE 37-SI Micr...)","O2 [µmol/l] (Oxygen optode, Aanderaa type ...)",O2 [µmol/l] (Corrected),DO [ml/l] (Corrected),O2 [mg/l] (Corrected),O2 sat [%] (Corrected),Latitude,Longitude,Station,Date,B01,B02,B03,B04,B05,B06,B07
0,2014-09-15 16:10:00,17.80,16.98,338.69,303.92,6.80,9.72,113.43,54.330192,10.149911,1,2014-09-15,0.003589,0.105031,0.001661,0.001464,0.024370,0.025011,0.001926
1,2014-09-15 16:20:00,17.81,16.97,339.23,304.41,6.82,9.74,113.64,54.330192,10.149911,1,2014-09-15,0.003589,0.105031,0.001661,0.001464,0.024370,0.025011,0.001926
2,2014-09-15 16:30:00,17.79,16.97,340.91,305.91,6.85,9.79,114.17,54.330192,10.149911,1,2014-09-15,0.003589,0.105031,0.001661,0.001464,0.024370,0.025011,0.001926
3,2014-09-15 16:40:00,17.80,16.97,340.46,305.51,6.84,9.77,114.03,54.330192,10.149911,1,2014-09-15,0.003589,0.105031,0.001661,0.001464,0.024370,0.025011,0.001926
4,2014-09-15 16:50:00,17.80,16.97,343.69,308.41,6.91,9.87,115.11,54.330192,10.149911,1,2014-09-15,0.003589,0.105031,0.001661,0.001464,0.024370,0.025011,0.001926
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
220440,2019-09-12 07:30:00,15.95,18.17,96.69,86.10,1.93,2.75,31.18,54.330192,10.149911,1,2019-09-12,1.030664,1.132340,0.985677,0.920928,1.129172,1.684503,0.882512
220441,2019-09-12 07:40:00,16.00,18.12,97.73,87.06,1.95,2.78,31.55,54.330192,10.149911,1,2019-09-12,1.030664,1.132340,0.985677,0.920928,1.129172,1.684503,0.882512
220442,2019-09-12 07:50:00,15.98,18.14,100.07,89.13,2.00,2.85,32.29,54.330192,10.149911,1,2019-09-12,1.030664,1.132340,0.985677,0.920928,1.129172,1.684503,0.882512
220443,2019-09-12 08:00:00,16.00,18.13,100.61,89.62,2.01,2.87,32.48,54.330192,10.149911,1,2019-09-12,1.030664,1.132340,0.985677,0.920928,1.129172,1.684503,0.882512
220444,2019-09-12 08:10:00,15.93,18.28,92.53,82.34,1.84,2.63,29.82,54.330192,10.149911,1,2019-09-12,1.030664,1.132340,0.985677,0.920928,1.129172,1.684503,0.882512

In [ ]:
merged_df.to_csv('salinity_germany_data.csv')